import { useState } from "react";
import { Link } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

type Lang = "pl" | "en";

// Company data — update when Companies House number is provided
const COMPANY = {
  name: "Zeta Core Ltd",
  number: "[Companies House No. — to be provided]",
  address: "London, United Kingdom",
  email: "contact@zeta-core-dsp.com",
  domain: "zeta-core-dsp.com",
};

const T = {
  pl: {
    title: "Informacje prawne — ZETA-CORE",
    subtitle: "O firmie, Polityka prywatności, Regulamin",
    back: "← Powrót do /zeta",
    aboutTitle: "O firmie",
    about: [
      `${COMPANY.name} to brytyjska spółka z siedzibą w Londynie, dostarczająca oprogramowanie diagnostyczne ZETA-CORE — silnik analizy koherencji fazowej dla maszyn wirujących (silniki, pompy, wentylatory, łożyska, przekładnie).`,
      `Numer w Companies House: ${COMPANY.number}. Siedziba: ${COMPANY.address}. Kontakt biznesowy: ${COMPANY.email}.`,
      `Model działalności: raporty diagnostyczne na żądanie, subskrypcja miesięcznego monitoringu floty, integracja Fleet API v3.0 dla klientów korporacyjnych.`,
    ],
    privacyTitle: "Polityka prywatności",
    privacy: [
      "Dane osobowe przetwarzane są zgodnie z UK GDPR i Data Protection Act 2018.",
      "Przetwarzamy wyłącznie dane niezbędne do świadczenia usługi: adres e-mail, nazwa firmy, dane techniczne przesłanych plików pomiarowych.",
      "Nagrania audio i pliki CSV przesyłane do portalu diagnostycznego NIE są trwale przechowywane — analiza odbywa się w pamięci funkcji brzegowej i wynik zwracany jest natychmiast.",
      "Nie sprzedajemy ani nie udostępniamy danych osobowych stronom trzecim.",
      "Prawo dostępu, sprostowania i usunięcia danych realizujemy w ciągu 30 dni od zgłoszenia na " + COMPANY.email + ".",
      "Pliki cookie: używamy wyłącznie technicznych plików sesyjnych niezbędnych do działania portalu.",
    ],
    termsTitle: "Regulamin świadczenia usług",
    terms: [
      `Usługodawca: ${COMPANY.name} (${COMPANY.address}).`,
      "Usługa: dostarczenie raportu diagnostycznego wygenerowanego przez silnik ZETA-CORE na podstawie danych przesłanych przez klienta.",
      "Klient odpowiada za zgodność przesłanych danych ze stanem faktycznym maszyny oraz za posiadanie prawa do ich udostępnienia.",
      "Raport diagnostyczny stanowi opinię techniczną opartą na analizie sygnału i NIE zastępuje pełnej inspekcji mechanicznej wykonanej przez uprawnionego inżyniera.",
      "Odpowiedzialność usługodawcy jest ograniczona do wysokości opłaty za dany raport lub miesięczną subskrypcję.",
      "Cennik: raport pojedynczy £200–£800, monitoring miesięczny od £400/maszyna, integracja Fleet API od £2500 (pilotaż 3-miesięczny).",
      "Faktury wystawiane są w GBP. Reklamacje: 14 dni od otrzymania raportu, na " + COMPANY.email + ".",
      "Prawo właściwe: prawo Anglii i Walii. Sądem właściwym są sądy w Londynie.",
    ],
    updated: "Ostatnia aktualizacja: 2026-07-18",
  },
  en: {
    title: "Legal Information — ZETA-CORE",
    subtitle: "About, Privacy Policy, Terms of Service",
    back: "← Back to /zeta",
    aboutTitle: "About the company",
    about: [
      `${COMPANY.name} is a UK-registered company based in London, providing the ZETA-CORE diagnostic software — a phase-coherence analytics engine for rotating machinery (motors, pumps, fans, bearings, gearboxes).`,
      `Companies House number: ${COMPANY.number}. Registered address: ${COMPANY.address}. Business contact: ${COMPANY.email}.`,
      `Business model: on-demand diagnostic reports, monthly fleet-monitoring subscriptions, and Fleet API v3.0 integrations for enterprise customers.`,
    ],
    privacyTitle: "Privacy Policy",
    privacy: [
      "Personal data is processed in accordance with UK GDPR and the Data Protection Act 2018.",
      "We process only the data required to deliver the service: email address, company name, and the technical content of measurement files you upload.",
      "Audio recordings and CSV files uploaded to the diagnostic portal are NOT persisted — analysis runs in-memory inside an edge function and the result is returned immediately.",
      "We do not sell or share personal data with third parties.",
      "Rights of access, rectification and deletion are handled within 30 days of a request sent to " + COMPANY.email + ".",
      "Cookies: only technical session cookies required for portal operation are used.",
    ],
    termsTitle: "Terms of Service",
    terms: [
      `Service provider: ${COMPANY.name} (${COMPANY.address}).`,
      "Service: delivery of a diagnostic report generated by the ZETA-CORE engine based on data supplied by the client.",
      "The client is responsible for ensuring the supplied data reflects the actual machine state and that they hold the right to share it.",
      "The diagnostic report is a technical opinion based on signal analysis and does NOT replace a full mechanical inspection carried out by a certified engineer.",
      "The provider's liability is limited to the amount paid for the individual report or the monthly subscription in question.",
      "Pricing: single report £200–£800, monthly monitoring from £400/machine, Fleet API integration from £2,500 (3-month pilot).",
      "Invoices are issued in GBP. Complaints: within 14 days of receiving the report, addressed to " + COMPANY.email + ".",
      "Governing law: laws of England and Wales. Exclusive jurisdiction: courts of London.",
    ],
    updated: "Last updated: 2026-07-18",
  },
};

export default function ZetaLegal() {
  const [lang, setLang] = useState<Lang>("pl");
  const t = T[lang];

  return (
    <div className="min-h-screen bg-background text-foreground p-4 md:p-8">
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <Link to="/zeta">
            <Button variant="ghost" size="sm">
              <ArrowLeft className="w-4 h-4 mr-2" />
              {t.back}
            </Button>
          </Link>
          <div className="flex gap-2">
            <Button size="sm" variant={lang === "pl" ? "default" : "outline"} onClick={() => setLang("pl")}>PL</Button>
            <Button size="sm" variant={lang === "en" ? "default" : "outline"} onClick={() => setLang("en")}>EN</Button>
          </div>
        </div>

        <div>
          <h1 className="text-3xl font-bold">{t.title}</h1>
          <p className="text-muted-foreground">{t.subtitle}</p>
        </div>

        <Card id="about">
          <CardHeader><CardTitle>{t.aboutTitle}</CardTitle></CardHeader>
          <CardContent className="space-y-3 text-sm leading-relaxed">
            {t.about.map((p, i) => <p key={i}>{p}</p>)}
          </CardContent>
        </Card>

        <Card id="privacy">
          <CardHeader><CardTitle>{t.privacyTitle}</CardTitle></CardHeader>
          <CardContent className="space-y-2 text-sm leading-relaxed">
            <ul className="list-disc pl-5 space-y-2">
              {t.privacy.map((p, i) => <li key={i}>{p}</li>)}
            </ul>
          </CardContent>
        </Card>

        <Card id="terms">
          <CardHeader><CardTitle>{t.termsTitle}</CardTitle></CardHeader>
          <CardContent className="space-y-2 text-sm leading-relaxed">
            <ol className="list-decimal pl-5 space-y-2">
              {t.terms.map((p, i) => <li key={i}>{p}</li>)}
            </ol>
          </CardContent>
        </Card>

        <p className="text-xs text-muted-foreground text-center">{t.updated}</p>
      </div>
    </div>
  );
}
