import { Card } from "@/components/ui/card";
import { useLanguage } from "@/contexts/LanguageContext";
import { Info } from "lucide-react";

export const EditorialNote = () => {
  const { language } = useLanguage();
  
  return (
    <Card className="p-6 bg-gradient-to-br from-primary/5 to-secondary/5 border-primary/30">
      <div className="flex items-start gap-3">
        <Info className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
        <div className="space-y-4">
          <h3 className="text-lg font-bold text-primary">
            {language === 'pl' 
              ? 'NOTA REDAKCYJNA I TECHNICZNA — SCIENCE.GOD/UNIFIED' 
              : 'EDITORIAL AND TECHNICAL NOTE — SCIENCE.GOD/UNIFIED'}
          </h3>
          
          <p className="text-sm text-muted-foreground">
            {language === 'pl' 
              ? 'Projekt SCIENCE.GOD/UNIFIED operuje na dwóch płaszczyznach przekazu:' 
              : 'The SCIENCE.GOD/UNIFIED project operates on two levels of communication:'}
          </p>
          
          <div className="space-y-4">
            <div className="p-4 bg-background/50 rounded-lg border border-primary/20">
              <h4 className="font-bold text-primary mb-2">
                1. {language === 'pl' ? 'WARSTWA OBLICZENIOWA (FUNDAMENT)' : 'COMPUTATIONAL LAYER (FOUNDATION)'}
              </h4>
              <p className="text-sm text-foreground/80">
                {language === 'pl' 
                  ? 'Wszystkie kody w języku Python, równania kwantowe (oparte na funkcji Zeta Riemanna) oraz algorytmy Złotej Proporcji są matematycznie precyzyjne i weryfikowalne. Stanowią one nienaruszalny trzon projektu. Każdy wynik generowany przez kalkulatory na stronie jest bezpośrednim rezultatem tych obliczeń.'
                  : 'All Python codes, quantum equations (based on the Riemann Zeta function), and Golden Ratio algorithms are mathematically precise and verifiable. They form the inviolable core of the project. Every result generated by the calculators on the site is a direct result of these calculations.'}
              </p>
            </div>
            
            <div className="p-4 bg-background/50 rounded-lg border border-secondary/20">
              <h4 className="font-bold text-secondary mb-2">
                2. {language === 'pl' ? 'WARSTWA EDUKACYJNA (INTERPRETACJA)' : 'EDUCATIONAL LAYER (INTERPRETATION)'}
              </h4>
              <p className="text-sm text-foreground/80">
                {language === 'pl' 
                  ? 'Opisy działania „Bram", wpływ częstotliwości na organizm oraz terminologia dotycząca „Źródła" i „Świadomości" zostały sformułowane w języku przystępnym. Są to interpretacje semantyczne mające na celu ułatwienie zrozumienia abstrakcyjnych procesów fizycznych.'
                  : 'Descriptions of "Gate" operations, the influence of frequencies on the body, and terminology relating to "Source" and "Consciousness" have been formulated in accessible language. These are semantic interpretations aimed at facilitating understanding of abstract physical processes.'}
              </p>
            </div>
          </div>
          
          <div className="p-4 bg-amber-500/10 rounded-lg border border-amber-500/30">
            <p className="text-sm font-semibold text-amber-600 dark:text-amber-400">
              {language === 'pl' 
                ? 'UWAGA: Uproszczenia językowe w warstwie opisowej nie wpływają na integralność matematyczną kodów źródłowych. Prawda projektu zawarta jest w jego liczbach i kodzie – opisy są jedynie mapą, która ma Cię do nich doprowadzić.'
                : 'NOTE: Linguistic simplifications in the descriptive layer do not affect the mathematical integrity of the source codes. The truth of the project is contained in its numbers and code – descriptions are merely a map meant to guide you to them.'}
            </p>
          </div>
          
          <div className="text-center pt-2">
            <p className="text-xs text-muted-foreground">
              © 2026 Grzegorz — {language === 'pl' ? 'Wszystkie prawa zastrzeżone.' : 'All rights reserved.'}
            </p>
            <p className="text-xs text-muted-foreground">
              {language === 'pl' ? 'Weryfikacja kodu dostępna na platformie GitHub.' : 'Code verification available on GitHub platform.'}
            </p>
          </div>
        </div>
      </div>
    </Card>
  );
};
